[development]
DB = "kongbot"
DB_HOST = "127.0.0.1"
DB_PORT = 27017
API_HOST = "0.0.0.0"
API_PORT = 3000
LOG_CONFIG = "log_config/logger_linux.yaml"
JWT_SECRET = "OIWNGOEG"

[production]
DB = "kongbot"
DB_HOST = "127.0.0.1"
DB_PORT = 27017
API_HOST = "0.0.0.0"
API_PORT = 3000
LOG_CONFIG = "log_config/logger_linux.yaml"
JWT_SECRET = "OIWNGOEG"