#!/bin/sh
export ENV_FOR_DYNACONF=production
export REACT_APP_API_ENDPOINT=http://18.221.129.100:8000

sudo lsof -t -i:8000 -sTCP:LISTEN | xargs -r kill

if [ "$1" = "server" ]; then
    cd KongServer
    screen -mS kongserver python3 app.py
else
    cd KongUI && npm run build
    cd ../KongServer
    screen -mS kongserver python3 app.py
fi
